name: The Final Boss Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Flutter (Cache Disabled)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: false # Disabled cache to ensure a 100% clean state

      - name: 3. Clean Project Thoroughly
        run: flutter clean

      - name: 4. Force Overwrite pubspec.yaml
        run: |
          cat > pubspec.yaml << EOF
          name: final_project
          description: "A new Flutter project."
          publish_to: "none"
          version: 1.0.0+1
          environment:
            sdk: ">=3.4.0 <4.0.0"
          dependencies:
            flutter:
              sdk: flutter
            cupertino_icons: ^1.0.8
            dio: ^5.8.0+1
            flutter_bloc: ^9.1.1
            firebase_core: ^2.30.0
            firebase_auth: ^4.17.8
            google_sign_in: ^6.2.1
            shared_preferences: ^2.0.15
            equatable: ^2.0.5
            connectivity_plus: ^6.0.1
            image_picker: ^1.1.2
            flutter_credit_card: ^4.0.1
          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^4.0.0
          flutter:
            uses-material-design: true
            assets:
              - assets/onboarding/
              - assets/icons/
              - assets/logos/
              - assets/shoes/
          EOF

      - name: 5. Force Create Podfile
        run: |
          cat > ios/Podfile << EOF
          platform :ios, '13.0'
          eval(File.read(File.join('..', '.flutter', 'ios_podhelper.rb')), binding)
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF

      - name: 6. Add GoogleService-Info.plist from Secret
        env:
          GOOGLE_SERVICE_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
        run: |
          echo $GOOGLE_SERVICE_PLIST_BASE64 | base64 --decode > $GITHUB_WORKSPACE/ios/Runner/GoogleService-Info.plist

      - name: 7. Get Dependencies
        run: flutter pub get

      - name: 8. Verify Critical File Generation
        run: |
          if [ ! -f ".flutter/ios_podhelper.rb" ]; then
            echo "FATAL ERROR: flutter pub get FAILED to create the critical ios_podhelper.rb script. This is the root cause."
            exit 1
          else
            echo "SUCCESS: The critical ios_podhelper.rb script was found. Proceeding to build."
          fi

      - name: 9. Build IPA
        run: flutter build ipa --release --no-codesign

      - name: 10. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa
